version: '3'
services:
  simulation:
    image: fieldrobotevent/simulation
    container_name: simulation
    volumes:
      - "~/simulation_assets/map:/simulation_ws/src/virtual_maize_field/map"
      - "~/simulation_assets/Media:/simulation_ws/src/virtual_maize_field/Media"
      - "~/simulation_assets/worlds:/simulation_ws/src/virtual_maize_field/worlds"
      - "~/simulation_assets/launch:/simulation_ws/src/virtual_maize_field/launch"
      - "~/simulation_assets/gzweb:/gzweb/http/client/assets"
      - "~/simulation_assets/robot_packages:/simulation_ws/src/robot_packages"
    ports:
    - "8080:8080"
    - "11345:11345"

  robot_container:
    depends_on:
    - "simulation"
    image: robot_workspace
    container_name: robot
    volumes:
      - "~/simulation_assets/map:/catkin/src/virtual_maize_field/map"
      - "~/simulation_assets/launch:/catkin/src/virtual_maize_field/launch"
    environment:
      - TASK_NUMBER=1

