version: '3'
services:
  simulation:
    image: fieldrobotevent/simulation:latest
    container_name: simulation
    volumes:
      - "../simulation_files/map:/simulation_ws/src/virtual_maize_field/map"
      - "../simulation_files/Media:/simulation_ws/src/virtual_maize_field/Media"
      - "../simulation_files/worlds:/simulation_ws/src/virtual_maize_field/worlds"
      - "../simulation_files/launch:/simulation_ws/src/virtual_maize_field/launch"
      - "../simulation_files/models:/simulation_ws/src/virtual_maize_field/models"
      - "../simulation_files/gt:/simulation_ws/src/virtual_maize_field/gt"
      - "../simulation_files/gzweb:/gzweb/http/client/assets"
      - "../simulation_files/robot_packages:/simulation_ws/src/robot_packages"
    ports:
    - "8080:8080"
    - "11345:11345"
    networks:
      competition_network:
        ipv4_address: 172.20.0.5
    environment:
      - ROS_IP=172.20.0.5 

  robot_container:
    depends_on:
    - "simulation"
    image: robot_workspace
    container_name: robot
    volumes:
      - "../simulation_files/map:/catkin/src/virtual_maize_field/map"
      - "../simulation_files/launch:/catkin/src/virtual_maize_field/launch"
      - "../simulation_files/models:/catkin/src/virtual_maize_field/models"
    environment:
      - TASK=navigation
    networks:
      competition_network:
        ipv4_address: 172.20.0.6

networks:
  competition_network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/24 
