version: '3'
services:
  simulation:
    image: fieldrobotevent/simulation-cuda:latest
    container_name: simulation
    volumes:
      - "../simulation_files/map:/simulation_ws/src/virtual_maize_field/map"
      - "../simulation_files/Media:/simulation_ws/src/virtual_maize_field/Media"
      - "../simulation_files/worlds:/simulation_ws/src/virtual_maize_field/worlds"
      - "../simulation_files/launch:/simulation_ws/src/virtual_maize_field/launch"
      - "../simulation_files/rviz:/simulation_ws/src/virtual_maize_field/rviz"
      - "../simulation_files/models:/simulation_ws/src/virtual_maize_field/models"
      - "../simulation_files/robot_packages:/simulation_ws/src/robot_packages"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/tmp/.docker.xauth:/tmp/.docker.xauth"
    ports:
    - "11345:11345"
    networks:
      competition_network:
        ipv4_address: 172.20.0.5
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XAUTHORITY=/tmp/.docker.xauth
      - ROS_IP=172.20.0.5 
      - TASK=mapping
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  robot_container:
    depends_on:
    - "simulation"
    image: robot_workspace
    container_name: robot
    volumes:
      - "../simulation_files/map:/catkin/src/virtual_maize_field/map"
      - "../simulation_files/launch:/catkin/src/virtual_maize_field/launch"
      - "../simulation_files/models:/catkin/src/virtual_maize_field/models"
    networks:
      competition_network:
        ipv4_address: 172.20.0.6
    environment:
      - TASK=mapping
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

networks:
  competition_network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.20.0.0/24 
