name: Build GZWeb simulation

# Only trigger when we make a change to the dockerfile
on:
  push:
    branches:
      - main
    paths:
    - 'dockerfiles/simulation/**'
  workflow_dispatch:


jobs:
  build_gzweb_simulation:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: dockerfiles/simulation
          push: true
          tags: fieldrobotevent/simulation:latest
 