name: Publish to Dockerhub

# Only trigger when we make a change to the simulation container
on:
  push:
    branches:
      - main
    paths:
    - 'dockerfiles/**'
  workflow_dispatch:


jobs:
  simulation:
    strategy:
      matrix:
        image: ["simulation", "simulation_nvidia"]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: dockerfiles/${{ matrix.image }}
          push: true
          tags: fieldrobotevent/${{ matrix.image }}:latest
